### ISSUE TITLE
Estandarización de nombres de áreas

### ISSUE THREAD

**Issue by IgnacioOv** [inkua/inkua-principal-workspace#21]
Me ha llamado la atención el hecho de que en algunos nombres de áreas, no es posible utilizar la letra eñe, por lo tanto propongo poner un estándar y nombrar a todas las áreas con su equivalente en ingles con el fin de evitar estos problemas.

**Comment by LucasAlvarez99** [comment]
genial ignacio vamos con esa.

**Comment by frankinkua** [comment]
Lo voy a sumar como tema a discusión para el próximo foro de directores
Para estar 100% claro la idea es pasar de: **Area-Diseno -> Design-Area** ?

**Comment by frankinkua** [comment]
Cerramos esto con @IgnacioOv !!! todo muy prolijo ahora.
